version: '3'

services:
  gamepublisherapi:
    image: wfigueiredo/gamepublisherapi:latest
    container_name: gamepublisherapi
    env_file:
     - api.env
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
     - "5000:80"