version: '3.5'

services:
  gameclientapi:
    image: wfigueiredo/gameclientapi:latest
    container_name: gameclientapi
    env_file:
     - gameclientapi.env
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
     - "5000:80"
    networks:
      - services-network
    
networks:
  services-network:
    driver: bridge
    
volumes:  
  postgres_data: